sonar.organization=rakotobemandresyvoaharyambininintsoa
sonar.projectKey=rakotobemandresyvoaharyambininintsoa_crm-analytics
sonar.sources=frontend
sonar.exclusions=frontend/node_modules/**,frontend/.next/**,frontend/coverage/**
sonar.tests=frontend
sonar.test.inclusions=frontend/**/*.test.ts,frontend/**/*.test.tsx
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
